### ISSUE TITLE
IL: duplicate bills in Pupa DB

### ISSUE THREAD

**Issue by estaub** [openstates/openstates-scrapers#2396]
State: IL

Hundreds or probably thousands of bills appear to be duplicated.  Example API2 query:

```gql
{
  bill(jurisdiction: "Illinois", identifier: "HB 1055", session: "100th") {
    id
    identifier
  }
}
```
returns the error:

`get() returned more than one Bill -- it returned 2!`

**Comment by jamesturk** [comment]
thanks for the heads up, I think I know which change is responsible for
this.  it'll require a bit of DB surgery, but we've also been looking at a
hard reset of the alpha data in preparation to move to beta, I'll see how
complex it is and if it can be done separately

**Comment by jamesturk** [comment]
oh in the mean time try adding the fully qualified jurisdiction:

{
  bill(jurisdiction: "ocd-jurisdiction/country:us/state:il/government",
identifier: "HB 1055", session: "100th") {
    id
    identifier
  }
}
