### ISSUE TITLE
API returning "not available" for identifiers ...

### ISSUE THREAD

**Issue by Deskimo** [openstates/openstates-scrapers#2792]
All of the new additions from our API calls are returning "~not available~" as the value for "identifier": 

http://openstates.org/api/v1/legislators/?active=true&chamber=upper&state=NV&apikey=API-KEY-GOES-HERE

for e.g.

{
+    "all_ids": [
+      "~not available~"
+    ], 
+    "district": "87", 
+    "email": "Renee.Erickson@house.ks.gov", 
+    "first_name": "Renee", 
+    "identifier": "~not available~", 
+    "last_name": "Erickson", 
+    "party": "Republican", 
+    "photo": "http://www.kslegislature.org/li/m/images/pics/rep_erickson_renee_1.jpg", 
+    "primary_phone": "785-296-7476", 
+    "source_url": "http://openstates.org/api/v1/legislators/?active=true&chamber=lower&state=ks&apikey=API-KEY-GOES-HERE"
+  },

**Comment by jlev** [comment]
Is there another ID we can use for caching results on our client side?
I'd be happy to use the OCDID, but I'm not seeing that come through as a field.

**Comment by jamesturk** [comment]
Is it possible to use a compound key for your caching?
state-session-bill_id works as unique, but we can also look at exposing the
ocd-bill ID via the v1 API

**Comment by jlev** [comment]
I ended up rewriting against the GraphQL endpoint, so this issue is now moot for me.

In principle, I'd support returning something unique for the legislator id, instead of \~not available\~, which ended up tripping up my cache. But you've given us plenty of notice about v2, so that's fair.
