### ISSUE TITLE
Common media_type parser

### ISSUE THREAD

**Issue by showerst** [openstates/openstates-scrapers#3177]
State: All

@jamesturk what do you think about me adding a url -> media_type function to a utils file? I feel like we have 

```if url.lower().endswith('.pdf'):``` 

... all over the place, it would be nice to centralize it.

I'm thinking just a simple string matcher, nothing that actually downloads or HEAD requests the file or anything.

**Comment by jamesturk** [comment]
that sounds great 👍

**Comment by showerst** [comment]
I have an open PR where i started this, that i intend to pick back up when there's free time, so ok to close this issue.
