### ISSUE TITLE
VA bills missing some information

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates-scrapers#3227]
from a user:

Both these two bills have had status updates with one being signed and enacted, yet your website doesn’t reflect said changes at all….

Seems like your website hasn’t been pulling the latest data form the “View Latest Bill Context” button. 

https://openstates.org/va/bills/2020/SB268/ 

https://openstates.org/va/bills/2020/HB888/

**Comment by showerst** [comment]
(i'm looking at this too since we're missing actions)

I think it's [this line](https://github.com/openstates/openstates/blob/master/openstates/va/bills.py#L389), that's resulting in the pairwise() function dropping the last list element (action) sometimes.

Any idea why that's there? I don't want to comment it out if we need it elsewhere or the last list el is sometimes bad.

**Comment by jamesturk** [comment]
ping @csnardi

**Comment by csnardi** [comment]
Hm, maybe I'm just missing it, but the LIS page on VA's website doesn't seem to show either bill as signed by the governor? They just show presentation to the governor, which the scraper picked up.

**Comment by showerst** [comment]
http://lis.virginia.gov/cgi-bin/legp604.exe?201+sum+SB268

SB 268 was signed

> 03/06/20  Governor: Approved by Governor-Chapter 191 (effective 7/1/20)

**Comment by csnardi** [comment]
Yep, deleted my comment since I somehow missed that one. Digging now...

**Comment by showerst** [comment]
I just pushed a branch, tim/2020/va-lastaction-debug that ONLY scrapes that bill, and comments out the line i flagged.

**Comment by csnardi** [comment]
Yep, that helped. I have a change to fix it that I'll push in a second.

**Comment by csnardi** [comment]
We're now picking up the actions correctly but the Senate bill linked above hasn't been updated. It looks like this is because the scraper doesn't pick up every bill:

```
02:54:50 INFO scrapelib: GET - http://lis.virginia.gov/cgi-bin/legp604.exe?201+lst+ALL+HB1107
import jurisdictions...
```

So I guess the website is returning a 200 with no content? Or some other broken page that would show no bills and no next page.

**Comment by schneidy** [comment]
All bills mentioned within this issue are now updated due to the new bill scraper for VA.
