### ISSUE TITLE
Montana votes issue

### ISSUE THREAD

**Issue by sActiVote** [openstates/openstates-scrapers#3299]
In the MT_2019_bills.csv there are 1309 bills which all have "upper" as their organization, suggesting these are all senate bills. In the MT_2017_bills.csv there are 1187 bills, which are split 710-lower and 477-upper. 

I believe that the 1309 bills from MT_2019_bills.csv also are the combination of all upper (Senate) and lower (House) bills. And thus, that the field is filled in incorrectly. 

This can easily be seen from the vote counts in MT_2019_vote_counts.csv (there are several vote events that have a total vote count of 100 (the number of legislators in the lower legislative body) as opposed to 50 (the number of legislators in the upper legislative body). 

Also, there are many votes in MT_2019_vote_people.csv that are clearly by lower legislator members (e.g: Bahr, Jade).

**Comment by jamesturk** [comment]
thanks for the catch, fixed the source data!
