### ISSUE TITLE
VA: HB 1547 needs to be updated

### ISSUE THREAD

**Issue by SS-Simon** [openstates/openstates-scrapers#3301]
State: VA 

https://lis.virginia.gov/cgi-bin/legp604.exe?201+sum+HB1547=&201+sum+HB1547=

It was approved by the governor.

**Comment by jamesturk** [comment]
fix in place, running today

**Comment by schneidy** [comment]
The latest update that we pushed to VA works. [HB 1547 on OpenStates](https://openstates.org/va/bills/2020/HB1547/) now shows the governor's approval.
