### ISSUE TITLE
WY: 2020 Special Session

### ISSUE THREAD

**Issue by jessemortenson** [openstates/openstates-scrapers#3331]
State: WY

Looks like Wyoming has a special session this year with about 6 bills, that isn't being picked up by the scraper: https://www.wyoleg.gov/Legislation/2020?specialSessionValue=1

This might be the cause of the 404 errors the scraper was encountering recently - bills like SF 1003 appear in normal bill search results, but result in a 404 from their internal API when you try to go to the bill page: https://www.wyoleg.gov/Legislation/2020/SF1003 - makes a request that 404s at https://web.wyoleg.gov/LsoService/api/BillInformation/2020/SF1003?specialSessionValue=

It only works when you go first to the special session link above, then to the bill from that list, eg https://wyoleg.gov/Legislation/2020/SF1003?specialSessionValue=1 then the request works (https://web.wyoleg.gov/LsoService/api/BillInformation/2020/SF1003?specialSessionValue=1)

**Comment by showerst** [comment]
Working on this, hope to have a PR for it today.

**Comment by showerst** [comment]
Looks like this is working now.
