### ISSUE TITLE
CA AB392

### ISSUE THREAD

**Issue by berger156** [openstates/openstates-scrapers#3360]
State: CA

The progress bar for CA AB392 (https://openstates.org/ca/bills/20192020/AB392/) is inconsistent with the list of actions. Namely, the Actions indicates Approval by the Governor and Chaptered by the Secretary of State on 8/19/19, but the progress bar indicates that the bill has stalled with the Governor.

**Comment by Almenon** [comment]
Same issue with https://openstates.org/ca/bills/20172018/SB1421/

It has been approved by the governor but is not marked as such. You can additionally verify that it was approved by the governor in this pdf doc: https://www.lacba.org/docs/default-source/lal-magazine/2019-test-articles/february2019testarticle.pdf

**Comment by showerst** [comment]
@jamesturk AB392 is getting properly classified (executive-signature on "Approved by the Governor.") so I think this is a frontend display issue.

**Comment by jamesturk** [comment]
Thanks, I'll take a look at what's going on here under the hood & update the issue as needed

**Comment by jamesturk** [comment]
fixed in latest develop branch, will be fixed on next deploy
