### ISSUE TITLE
LA 2020 regular session new bills not being ingested

### ISSUE THREAD

**Issue by jessemortenson** [openstates/openstates-scrapers#3361]
State: LA - Louisiana

Looks like some bills are being filed in the 2020 regular session, even though 2020s1 special session has begun. Examples include:

* [HCR 98](https://legis.la.gov/legis/BillInfo.aspx?i=239107&sbi=y)
* [HR 58](https://legis.la.gov/legis/BillInfo.aspx?i=239088&sbi=y)
* [SR 68](https://legis.la.gov/legis/BillInfo.aspx?i=239091&sbi=y)

The current LA-scrape scraper is doing 2020s1

Is it possible for OS to scrape multiple sessions in the same jurisdiction at the same time? or is that blocked due to operations reasons?

**Comment by jamesturk** [comment]
I can get things set up tomorrow to grab both, thanks for the heads up

**Comment by jessemortenson** [comment]
Looks like this has been addressed, though the special session scrape job appears not to have run yet... ?

**Comment by jamesturk** [comment]
it has run now :)
