### ISSUE TITLE
Link to contributing on readme.md is broken 

### ISSUE THREAD

**Issue by thefuturewasnow** [openstates/openstates-scrapers#3886]
@jamesturk this is my first commit, sorry if it's in the wrong place! The link in the [bottom of the readme.md](https://github.com/openstates/openstates-scrapers#links) for the Contributors Guide links to https://docs.openstates.org/en/latest/contributing/getting-started.html but it should be https://docs.openstates.org/contributing/
![Screen Shot 2021-12-14 at 1 57 49 PM](https://user-images.githubusercontent.com/1527431/146071017-63f3391a-6dc9-45d6-97b4-fe4d347534e9.png)

**Comment by jamesturk** [comment]
thanks for flagging this, you mention a commit but I didn't see the PR, I can fix this too but if you already had a PR somewhere glad to accept it!

**Comment by thefuturewasnow** [comment]
Hi James! I misspoke 🙃. I should have stated that it was my first "contribution." I need to relearn how to suggest a commit. If you could change it that would be great. I think the process is to make a "pull request" with the change but I don't know how to do that properly.
