### ISSUE TITLE
KY Bill Data Not Updating

### ISSUE THREAD

**Issue by njsortor** [openstates/openstates-scrapers#3927]
State: KY 

The data for the 2022 Kentucky State Legislative Session (which began Jan 4) is not updating. The most recent updates were from the 2021 Special Session back in September.

Open States Data: https://openstates.org/ky/bills/
KY Legislature Data: https://apps.legislature.ky.gov/record/22rs/record.html

This repository is for issues with state data.

For feature requests, etc. please visit the contributor guide (see above message) to file the issue in the correct place.

**Comment by NewAgeAirbender** [comment]
Thanks for flagging this, fix is live and 2022 bills are updating!
